### ISSUE TITLE
Image push is failing

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/oslo#117]
### Summary

When running actions on a PR, the image push step is failing with a 403.  [Example](https://github.com/OpenSLO/oslo/runs/6476458309?check_suite_focus=true)

### Steps to reproduce

Create a PR on a remote branch and notice that the image push step will fail, and the checks in the PR will fail.

**Comment by proffalken** [comment]
This looks to be a Github Token permissions thing, but I don't have access to the settings on this repo to confirm that.

https://github.com/OpenSLO/oslo/blob/main/.github/workflows/build_containers.yml#L52-L57 and https://github.com/OpenSLO/oslo/blob/main/.github/workflows/build_containers.yml#L68-L77 are the related lines of code.

Searching through the history of the action, it looks like https://github.com/docker/build-push-action/issues/463#issuecomment-1125443655 may hold the solution?

**Comment by ian-bartholomew** [comment]
This seems to be mostly working now, with only occasional failures.  Closing for now, but lets keep an eye on it

**Comment by kenfinnigan** [comment]
Just verified it's still broken, at least for my PRs -> https://github.com/OpenSLO/oslo/runs/6888000106?check_suite_focus=true

Is it an issue with who has created the PR?

**Comment by proffalken** [comment]
@kenfinnigan it shouldn't be - if this is setup in the same way I've done it in the past it uses a dedicated token that's generated specifically for each run.

I've requested that the job is re-run with debug logging enabled: https://github.com/OpenSLO/oslo/runs/6894358281?check_suite_focus=true

**Comment by proffalken** [comment]
I've just checked and a dependabot PR was pushed successfully after merge, @kenfinnigan - can you ensure you've rebased and then push your changes again to see if this is still an issue?

**Comment by kenfinnigan** [comment]
@proffalken I've just rebased and force pushed, lets see what happens

**Comment by proffalken** [comment]
I see this failed again.

I'm not too sure why it's doing this, as previous changes have built/merged fine:

![image](https://user-images.githubusercontent.com/262545/176463868-3991da53-3428-4050-b509-5d606ac289a3.png)

It's also one of those things that is *really* hard to test as you can only test the permissions thing within Github actions.

@ian-bartholomew - can you check and see if there are any permissions differences for @kenfinnigan vs others who have had successful builds please, just in case it's something along those lines causing this?

**Comment by proffalken** [comment]
OK, I think I may know what's causing this.

The branch that we're trying to build on is for @kenfinnigan's fork of the repo, not the core, so the images are probably being pushed to Ken's repo as well instead of here.

The code for the ones that has run successfully is in the main repo, not a fork>

@kenfinnigan can you try cloning the main repo and porting your work onto a branch from openslo/oslo so we can test this theory?

**Comment by kenfinnigan** [comment]
Now that you say that, the message makes sense.

I can create a PR from branch in main repo as a test, but we should definitely fix it for wider community adoption to use forks

**Comment by kenfinnigan** [comment]
@proffalken Looks like that did the trick. Updated the PR and CI now passed! Cheers!

**Comment by proffalken** [comment]
Huzzah!
