### ISSUE TITLE
[Question] v1 stable api release date

### ISSUE THREAD

**Issue by alexandreLamarre** [OpenSLO/oslo#125]
As the title says, I was wondering if there was already a date/timeline in mind for the v1 api?

**Comment by kenfinnigan** [comment]
There's a thread in Slack on what's required to finalize some items for v1.

We definitely want to have them resolved soon, but we don't have a specific date at present

**Comment by ian-bartholomew** [comment]
@alexandreLamarre yeah, like @kenfinnigan said, we have a thread in the slack about it.  But also in terms of support for the OpenSLO v1 Spec, it has it as of https://github.com/OpenSLO/oslo/pull/107

**Comment by ian-bartholomew** [comment]
@alexandreLamarre v0.4.0 of `oslo` was released just now with the v1 OpenSLO API spec support

**Comment by alexandreLamarre** [comment]
Awesome! Thank you
