### ISSUE TITLE
Oslo does not have a --version command

### ISSUE THREAD

**Issue by proffalken** [OpenSLO/oslo#133]
### Summary

When running Oslo, I wanted to confirm that I was running the latest version.  This information is not output as part of `--help`, and there is no `--version` tag, so it is difficult to check which version is running.

### Steps to reproduce

1. Build Oslo from source or download it from Github
2. Execute `oslo -h`, `oslo --help`, or `oslo --version`
3. Observe that none of the commands print a version number

### What is the current *bug* behavior?

The version is not available

### What is the expected *correct* behavior?

I'd expect to see a version number printed to the console

### Relevant logs and/or screenshots

```
oslo help
Oslo is a CLI tool for the OpenSLO spec

Usage:
  oslo [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  fmt         Formats the provided input into the standard format.
  help        Help about any command
  validate    Validates your yaml file against the OpenSLO spec.

Flags:
  -h, --help   help for oslo

Use "oslo [command] --help" for more information about a command.
```

### Possible fixes

Add code to output this value somehow?

**Comment by kenfinnigan** [comment]
I want clarify you're asking for the oslo cli version and not a version of supported OpenSLO spec versions for validation?

**Comment by proffalken** [comment]
@kenfinnigan sorry, yes, that is correct.  It is the version of the oslo cli that I am looking for here

**Comment by kenfinnigan** [comment]
Thanks for confirming. Did you mean to close the issue?

**Comment by proffalken** [comment]
lol, I did not, I pressed the wrong button! :D

**Comment by proffalken** [comment]
OK, so it looks like `<ctrl>+enter` now closes issues by default rather than just commenting on them...
