### ISSUE TITLE
Add an example of an oslo spec file in the readme

### ISSUE THREAD

**Issue by rajbos** [OpenSLO/oslo#15]
I got directed here from a tweet and expected more information about for example the specification file. Had to go to the website and then back to [https://github.com/openslo/openslo](https://github.com/openslo/openslo) to get more information. 

Adding  a sample like available in the test folder (e.g. : [valid-slos-ratio.yaml](https://github.com/OpenSLO/oslo/blob/main/test/valid-slos-ratio.yaml)) would make things a lot more clear.

**Comment by nieomylnieja** [comment]
I think https://github.com/OpenSLO/OpenSLO has it all covered in great detail. If you feel like the header description of the project is too vague in pointing to the specification, feel free to reopen this issue (suggestion how to rephrase it would be welcome :+1: ):

```
CLI tool for the OpenSLO spec. For more information also check the website: openslo.com.
```

**Comment by rajbos** [comment]
The repo README is a lot more clear than the website, but it is there now 😬. Thanks for closing this.
