### ISSUE TITLE
Make passing of files and directories as arguments cohesive across oslo commands

### ISSUE THREAD

**Issue by programmer04** [OpenSLO/oslo#220]
### Problem to solve

Currently, the usage of commands `validate`, `convert`, and `fmt` differs in how files are passed to them.

```sh
oslo validate file1.yml file2.yml
```
Passing without any flags for single or multiple files. A directory can't be passed as an argument (I don't count using shell wildcard expansion).

```sh
oslo convert -f file1.yml -f file2.yml
```
Flag `--file | -f` is required to pass single or multiple files. For passing a directory as an argument separate flag `--directory | -d` that does not work recursively, furthermore when the directory contains a directory it fails.

```sh
oslo fmt file1.yml
```
the above is similar too `validate`, but allows only passing one file.

### Proposal

I think we should make it cohesive. In my opinion, replicating `kubectl` behavior is a good choice.
Every time flag `--file | -f` is required. It accepts a single file or directory (for a directory does not traverse, it reads only files from its root). To process a directory recursively (the content of it and its subdirectories arbitrarily deep) use the flag `--recursive | -R`. Using the flag `--recursive | -R` when a path to a file is passed instead of a directory does not break anything. 

### Further details

**It would be a breaking change!!!** ensure that it'll be properly marked in release notes.

**Comment by kenfinnigan** [comment]
Alignment sounds like a good idea, and I agree with the proposal
