### ISSUE TITLE
Consider cue for heavy lifting

### ISSUE THREAD

**Issue by embano1** [OpenSLO/oslo#23]
Given the current feature set is on validation, I was wondering if using cue (pkg or CLI) can have a positive overall impact on OpenSLO tooling and schema definition (separate repo)?

https://cuelang.org/ has lots of benefits and gains more traction every day, especially in the K8s ecosystem, to define, validate and export configuration schemas. 

Thoughts?

**Comment by ian-bartholomew** [comment]
Responded in https://github.com/OpenSLO/OpenSLO/issues/20

**Comment by ian-bartholomew** [comment]
Going to close this one, and keep it going in https://github.com/OpenSLO/OpenSLO/issues/20

**Comment by yonkeltron** [comment]
Would it be appropriate to also consider JSON Schema as a more neutral format since it can be used for code generation with things like [Quicktype](https://quicktype.io/)?
