### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/oslo#6]
In order to help foster an inclusive community, we should add and adopt a code of conduct.  This one would a be a reasonable one to adopt: https://www.contributor-covenant.org/version/2/0/code_of_conduct/

**Comment by jetzlstorfer** [comment]
Seems to be already addressed: https://github.com/OpenSLO/oslo/blob/main/CODE_OF_CONDUCT.md

**Comment by ian-bartholomew** [comment]
@jetzlstorfer you are right, I forgot to close this.  Thanks!
