### ISSUE TITLE
Add support for `Bad` metrics from OpenSLO PR #45

### ISSUE THREAD

**Issue by nobl9-mikec** [OpenSLO/oslo#62]
### Problem to solve

Currently out of sync with OpenSLO after merging support for `Bad` metrics : https://github.com/OpenSLO/OpenSLO/issues/45

Including such metrics in an SLO yaml right now results in the following errors: 
```
Error: Key: 'SLO.Spec.Objectives[0].RatioMetrics.Good.Source' Error:Field validation for 'Source' failed on the 'required' tag
Key: 'SLO.Spec.Objectives[0].RatioMetrics.Good.QueryType' Error:Field validation for 'QueryType' failed on the 'required' tag
Key: 'SLO.Spec.Objectives[0].RatioMetrics.Good.Query' Error:Field validation for 'Query' failed on the 'required' tag
```

### Proposal

We should update validation to account for the new supported OpenSLO functionality

**Comment by kenfinnigan** [comment]
Resolved by https://github.com/OpenSLO/oslo/pull/107
